force-app/main/default/objects/Batch_Log__c/Batch_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Log</label>
    <nameField>
        <label>Batch Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Log__c/fields/Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Batch_Scope__c.field-meta.xml
<CustomField>
    <fullName>Batch_Scope__c</fullName>
    <label>Batch Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Batch_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Batch_Start_Date__c</fullName>
    <label>Batch Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Batch_Type__c.field-meta.xml
<CustomField>
    <fullName>Batch_Type__c</fullName>
    <label>Batch Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>SharingRecalculation</fullName>
            </value>
            <value>
                <fullName>ScheduledApex</fullName>
            </value>
            <value>
                <fullName>BatchApex</fullName>
            </value>
            <value>
                <fullName>BatchApexWorker</fullName>
            </value>
            <value>
                <fullName>TestRequest</fullName>
            </value>
            <value>
                <fullName>TestWorker</fullName>
            </value>
            <value>
                <fullName>ApexToken</fullName>
            </value>
            <value>
                <fullName>Queueable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Chunks_Processed__c.field-meta.xml
<CustomField>
    <fullName>Chunks_Processed__c</fullName>
    <label>Chunks Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Chunks_With_Errors__c.field-meta.xml
<CustomField>
    <fullName>Chunks_With_Errors__c</fullName>
    <label>Chunks With Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Cron_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Cron_Trigger__c</fullName>
    <label>Cron Trigger</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/DML_Type__c.field-meta.xml
<CustomField>
    <fullName>DML_Type__c</fullName>
    <label>DML Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Items_in_Scope__c.field-meta.xml
<CustomField>
    <fullName>Items_in_Scope__c</fullName>
    <label>Items in Scope</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Items_Processed__c.field-meta.xml
<CustomField>
    <fullName>Items_Processed__c</fullName>
    <label>Items Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Number_Of_DML_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_DML_Errors__c</fullName>
    <label>Number of DML Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Number_of_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Errors__c</fullName>
    <label>Number of Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holding</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Total_Batch_Chunks__c.field-meta.xml
<CustomField>
    <fullName>Total_Batch_Chunks__c</fullName>
    <label>Total Batch Chunks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchMonitorSelectors.cls
public with sharing class BatchMonitorSelectors {
  


    public static AsyncApexJob getAsyncApexJob(Set<Id> ids){
        AsyncApexJob job = [SELECT Id, JobType,Status,CompletedDate,MethodName,CreatedDate,JobItemsProcessed,ApexClass.Name,NumberOfErrors,TotalJobItems FROM AsyncApexJob WHERE Id = :ids LIMIT 1];
        return job;
    }

    public static Batch_Log__c getBatchJobLog(Set<Id> ids){
        Batch_Log__c log = [SELECT  Id,Apex_Class_Name__c, Batch_Id__c, Batch_Scope__c, Batch_Start_Date__c, Batch_Type__c, Chunks_Processed__c, Chunks_With_Errors__c, Completed_Date__c, CreatedById, CreatedDate, Cron_Trigger__c, DML_Type__c, Error_Message__c, Items_in_Scope__c, Items_Processed__c, Name, Number_Of_DML_Errors__c, Number_of_Errors__c, Stack_Trace__c, Status__c, Total_Batch_Chunks__c FROM Batch_Log__c WHERE Batch_Id__c = :ids LIMIT 1];
        return log;
    }





}