force-app/main/default/objects/Batch_Log__c/Batch_Log__c.object-meta.xml
<CustomObject>
    <label>Batch Log</label>
    <nameField>
        <label>Batch Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Log__c/fields/Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Batch_Scope__c.field-meta.xml
<CustomField>
    <fullName>Batch_Scope__c</fullName>
    <label>Batch Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Batch_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Batch_Start_Date__c</fullName>
    <label>Batch Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Batch_Type__c.field-meta.xml
<CustomField>
    <fullName>Batch_Type__c</fullName>
    <label>Batch Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>SharingRecalculation</fullName>
            </value>
            <value>
                <fullName>ScheduledApex</fullName>
            </value>
            <value>
                <fullName>BatchApex</fullName>
            </value>
            <value>
                <fullName>BatchApexWorker</fullName>
            </value>
            <value>
                <fullName>TestRequest</fullName>
            </value>
            <value>
                <fullName>TestWorker</fullName>
            </value>
            <value>
                <fullName>ApexToken</fullName>
            </value>
            <value>
                <fullName>Queueable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Chunks_Processed__c.field-meta.xml
<CustomField>
    <fullName>Chunks_Processed__c</fullName>
    <label>Chunks Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Chunks_With_Errors__c.field-meta.xml
<CustomField>
    <fullName>Chunks_With_Errors__c</fullName>
    <label>Chunks With Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/DML_Type__c.field-meta.xml
<CustomField>
    <fullName>DML_Type__c</fullName>
    <label>DML Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Items_Processed__c.field-meta.xml
<CustomField>
    <fullName>Items_Processed__c</fullName>
    <label>Items Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Number_Of_DML_Errors__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_DML_Errors__c</fullName>
    <label>Number of DML Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holding</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Log__c/fields/Total_Batch_Chunks__c.field-meta.xml
<CustomField>
    <fullName>Total_Batch_Chunks__c</fullName>
    <label>Total Batch Chunks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchLog.cls
public class BatchLog {
    
    public Batch_Log__c record;
    public AsyncApexJob job;

    public BatchLog (Batch_Log__c record,AsyncApexJob job ){
        this.record = record;
        this.job = job;
    }

    public BatchLog (AsyncApexJob job ){
        this.job = job;
    }

    public void generateDefaultBatchLog(){
        this.record = new Batch_Log__c();
        setDefaultBatchLogValues();
    }

    public void generateDefaultBatchLog(String soqlScope){
        this.record = new Batch_Log__c();
        this.record.Batch_Scope__c = soqlScope;
        setDefaultBatchLogValues();
    }

    private void setDefaultBatchLogValues(){
        this.record.Batch_Id__c = this.job.Id;
        this.record.Status__c = this.job.Status;
        this.record.Batch_Start_Date__c = this.job.CreatedDate;
        this.record.Apex_Class_Name__c = this.job.ApexClass.Name;
        this.record.Batch_Type__c = this.job.JobType; 
    }

    public void setFinalLogValues(){
        this.record.Completed_Date__c = this.job.CompletedDate;
        this.record.Items_Processed__c = this.job.JobItemsProcessed;
        this.record.Status__c = this.job.Status;
        this.record.Chunks_Processed__c = this.job.JobItemsProcessed;
        this.record.Total_Batch_Chunks__c = this.job.TotalJobItems;
        this.record.Chunks_With_Errors__c += this.job.NumberOfErrors;
    }

    public void setExceptionValues(Exception ex){
        this.record.Stack_Trace__c = ex.getStackTraceString();
        this.record.Error_Message__c = ex.getMessage();
        this.record.DML_Type__c = String.ValueOf(ex.getDmlType(0));
        this.record.Number_Of_DML_Errors__c += ex.getNumDml();
    }


    public void setExceptionValues(DMLException ex){
        this.record.Stack_Trace__c = ex.getStackTraceString();
        this.record.Error_Message__c = ex.getMessage();
        this.record.DML_Type__c = String.ValueOf(ex.getDmlType(0));
        this.record.Number_Of_DML_Errors__c += ex.getNumDml();
    }
}