force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>ERROR-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AssertException</fullName>
            </value>
            <value>
                <fullName>AuraException</fullName>
            </value>
            <value>
                <fullName>AuraHandledException</fullName>
            </value>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>BigObjectException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>ExternalObjectException</fullName>
            </value>
            <value>
                <fullName>FinalException</fullName>
            </value>
            <value>
                <fullName>FlowException</fullName>
            </value>
            <value>
                <fullName>HandledException</fullName>
            </value>
            <value>
                <fullName>IllegalArgumentException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoDataFoundException</fullName>
            </value>
            <value>
                <fullName>NoSuchElementException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
            <value>
                <fullName>SObjectException</fullName>
            </value>
            <value>
                <fullName>StringException</fullName>
            </value>
            <value>
                <fullName>TypeException</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Services/Logger.cls
public with sharing class Logger {

    public static final String BATCH_LOG_RECORD_TYPE = 'Async Log';
    public static final String STANDARD_LOG_RECORD_TYPE = 'Standard Log';

    public static final String FLOW_EXCEPTION_TYPE = 'FlowException';

    public static String batchLogRecordTypeId;
    public static String standardRecordTypeId;

    public static void generateLog(Exception record){

        Log newLog = new Log();
        
        newLog.createLog(record, getStandardLogRecordTypeId());
        insert newLog.getRecords();
    } 

    public static void generateLogs(List<Exception> exceptionRecords){

        Log newLog = new Log();
        
        for(Exception ex : exceptionRecords){
            newLog.createLog(ex, getStandardLogRecordTypeId());
        }
        insert newLog.getRecords();
    } 

    public static void generateLogs(List<BatchApexErrorEvent> batchErrorEvents){
        Log newLogs = new Log();

        for(BatchApexErrorEvent bex : batchErrorEvents){
            newLogs.createLog(bex, getBatchLogRecordTypeId());
        }
        insert newLogs.getRecords();
    }

    public static void generateFlowLog(String message,Boolean isException){

        Log newLog = new Log();
        newLog.createFlowLog(message, getStandardLogRecordTypeId(), isException);  
        newLog.getRecords()[0].Exception_Type__c = FLOW_EXCEPTION_TYPE;
        
        insert newLog.getRecords();
    }

    public static Id getStandardLogRecordTypeId(){
        if(standardRecordTypeId == null){
            standardRecordTypeId = Schema.SObjectType.Log__c.getRecordTypeInfosByName().get(STANDARD_LOG_RECORD_TYPE).getRecordTypeId();
        } 
        return standardRecordTypeId;
    }

    public static Id getBatchLogRecordTypeId(){
        if(batchLogRecordTypeId == null){
            batchLogRecordTypeId = Schema.SObjectType.Log__c.getRecordTypeInfosByName().get(BATCH_LOG_RECORD_TYPE).getRecordTypeId();
        } 
        return batchLogRecordTypeId;
    }

}