force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>ERROR-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Batch_Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Batch_Exception_Type__c</fullName>
    <label>Batch Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anonymous</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
            <value>
                <fullName>Batch Acs</fullName>
            </value>
            <value>
                <fullName>Batch Apex</fullName>
            </value>
            <value>
                <fullName>Batch Chunk Parallel</fullName>
            </value>
            <value>
                <fullName>Batch Chunk Serial</fullName>
            </value>
            <value>
                <fullName>Bulk Api</fullName>
            </value>
            <value>
                <fullName>Commerce Integration</fullName>
            </value>
            <value>
                <fullName>Discoverable Login</fullName>
            </value>
            <value>
                <fullName>Function Callback</fullName>
            </value>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>Inbound Email Service</fullName>
            </value>
            <value>
                <fullName>Invocable Action</fullName>
            </value>
            <value>
                <fullName>IoT</fullName>
            </value>
            <value>
                <fullName>Post Install Script</fullName>
            </value>
            <value>
                <fullName>Queueable</fullName>
            </value>
            <value>
                <fullName>Quick Action</fullName>
            </value>
            <value>
                <fullName>Remote Action</fullName>
            </value>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>Runtest Async</fullName>
            </value>
            <value>
                <fullName>Runtest Deploy</fullName>
            </value>
            <value>
                <fullName>Runtest Sync</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
            <value>
                <fullName>Synchronous</fullName>
            </value>
            <value>
                <fullName>Transaction Finalizer Queueable</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Records_In_Scope__c.field-meta.xml
<CustomField>
    <fullName>Records_In_Scope__c</fullName>
    <label>Records In Scope</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>Logs used for Exception logging</description>
    <label>LogEvent</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/classes/Models/Log.cls
public with sharing class Log {
        
    Log__c record;

    public Log(BatchApexErrorEvent e, Id RecordTypeId) {
        System.debug('Creating new Batch Error log record');
        this.record = new Log__c(
            Stack_Trace__c = e.StackTrace,
            Batch_Job_ID__c = e.AsyncApexJobId,
            Batch_Exception_Type__c = e.ExceptionType,
            Batch_Phase__c = e.Phase,
            Records_In_Scope__c	= e.JobScope,
            Log_Data__c = e.Message,
            RecordTypeId = RecordTypeId
        );
    }

    public Log(LogEvent__e e,Id RecordTypeId){
        System.debug('Creating new standard Log record');
        this.record = new Log__c(
            Stack_Trace__c = e.Stack_Trace__c,
            Quiddity__c = e.Quiddity__c,
            Severity__c = e.Severity__c,
            RecordTypeId = RecordTypeId
        );
    }

    public Log__c getRecord(){
        return this.record;
    }


}