force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <description>Wrapper object for exceptions thrown by Apex</description>
    <label>Exception</label>
    <nameField>
        <displayFormat>Ex-{00000000}</displayFormat>
        <label>Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/Exception_Source__c.field-meta.xml
<CustomField>
    <fullName>Exception_Source__c</fullName>
    <label>Exception Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExceptionManagerServiceImpl.cls
public with sharing class ExceptionManagerServiceImpl {
    
    public ExceptionManagerServiceImpl() {

    }


    public static void generateExceptionRecord(String stackTrace,String exceptionSource, String ExceptionType){


        Exception__c newExceptionRecord = new Exception__c();

        newExceptionRecord.Stack_Trace__c = stackTrace;
        newExceptionRecord.Exception_Source__c = exceptionSource;
        newExceptionRecord.Exception_Type__c = ExceptionType;



    }
}